# Generated by Django 5.1.8 on 2026-03-26 00:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_rename_mine_activi_name_aa0f66_idx_master_acti_name_e4fae2_idx_and_more'),
        ('selling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingBargingTemporaryView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_hauling', models.DateField(blank=True, default=None, null=True)),
                ('time_hauling', models.TimeField(blank=True, default=None, null=True)),
                ('barge_code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('shift', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('dome', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('stockpile', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('material', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('unit_code', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('tonnage', models.FloatField(blank=True, default=None, null=True)),
                ('code_lot', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('code_inc', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('code_sub', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('type_selling', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sale_adjust', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('no_urut', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, default=None, null=True)),
                ('user_id', models.IntegerField(blank=True, default=None, null=True)),
                ('username', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('iup_id', models.IntegerField(blank=True, default=None, null=True)),
                ('iup_code', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('iup_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'view_selling_barging_temporary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellingBargingTemporary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_lot', models.IntegerField(blank=True, default=None, null=True)),
                ('barge_code', models.IntegerField(blank=True, default=None, null=True)),
                ('date_hauling', models.DateField(blank=True, default=None, null=True)),
                ('time_hauling', models.TimeField(blank=True, default=None, null=True)),
                ('shift', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('id_material', models.IntegerField(blank=True, default=None, null=True)),
                ('id_stockpile', models.IntegerField(blank=True, default=None, null=True)),
                ('id_pile', models.IntegerField(blank=True, default=None, null=True)),
                ('unit_code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('tonnage', models.FloatField(blank=True, default=0, null=True)),
                ('type_selling', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('code_inc', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('code_sub', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('code_sub_auto', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('id_user', models.IntegerField(blank=True, default=None, null=True)),
                ('sale_adjust', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('no_urut', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('iup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.mineiup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sellings_barging_temporary',
            },
        ),
        migrations.DeleteModel(
            name='SellingDetailsBargingTempView',
        ),
        migrations.AddIndex(
            model_name='sellingbargingtemporary',
            index=models.Index(fields=['code_inc'], name='sellings_ba_code_in_ed8bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='sellingbargingtemporary',
            index=models.Index(fields=['sale_adjust'], name='sellings_ba_sale_ad_46938e_idx'),
        ),
        migrations.AddIndex(
            model_name='sellingbargingtemporary',
            index=models.Index(fields=['code_lot'], name='sellings_ba_code_lo_f70cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='sellingbargingtemporary',
            index=models.Index(fields=['code_sub'], name='sellings_ba_code_su_0955e5_idx'),
        ),
    ]
