# Generated by Django 5.1.8 on 2026-03-26 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_rename_mine_activi_name_aa0f66_idx_master_acti_name_e4fae2_idx_and_more'),
        ('selling', '0002_sellingbargingtemporaryview_sellingbargingtemporary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingBargingAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrival', models.DateField(blank=True, default=None, null=True)),
                ('date_departure', models.DateField(blank=True, default=None, null=True)),
                ('jetty_departure', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('ritase_ori', models.IntegerField(blank=True, default=None, null=True)),
                ('tonnage_ori', models.FloatField(blank=True, default=None, null=True)),
                ('tonnage_adjust', models.FloatField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'selling_barging_adjustment',
            },
        ),
        migrations.AddIndex(
            model_name='sellingbargingtemporary',
            index=models.Index(fields=['unit_code'], name='sellings_ba_unit_co_c47240_idx'),
        ),
        migrations.AddIndex(
            model_name='sellingbargingtemporary',
            index=models.Index(fields=['type_selling'], name='sellings_ba_type_se_a77ad6_idx'),
        ),
        migrations.AddField(
            model_name='sellingbargingadjustment',
            name='code_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='master.sellingcode'),
        ),
        migrations.AddField(
            model_name='sellingbargingadjustment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sellingbargingadjustment',
            index=models.Index(fields=['created_at'], name='selling_bar_created_1ca9db_idx'),
        ),
    ]
