# Generated by Django 5.1.8 on 2026-04-15 00:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_mineunitsexportview'),
        ('selling', '0003_sellingbargingadjustment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BargingPlan',
            fields=[
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_date', models.DateField(blank=True, default=None, null=True)),
                ('tugboat_name', models.CharField(blank=True, max_length=150, null=True)),
                ('barge_code', models.CharField(blank=True, max_length=150, null=True)),
                ('tonnage_plan', models.FloatField(blank=True, null=True)),
                ('no_plan', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('id_user', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.mineiup')),
            ],
            options={
                'db_table': 'selin_plan_barging',
                'indexes': [models.Index(fields=['iup'], name='selin_plan__iup_id_b1514e_idx'), models.Index(fields=['plan_date'], name='selin_plan__plan_da_2a5470_idx'), models.Index(fields=['barge_code'], name='selin_plan__barge_c_b2b3bd_idx'), models.Index(fields=['no_plan'], name='selin_plan__no_plan_6815ee_idx')],
            },
        ),
    ]
