# Generated by Django 5.1.8 on 2026-04-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0004_bargingplan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bargingplan',
            new_name='selling_pla_iup_id_04bfb8_idx',
            old_name='selin_plan__iup_id_b1514e_idx',
        ),
        migrations.RenameIndex(
            model_name='bargingplan',
            new_name='selling_pla_plan_da_fade7d_idx',
            old_name='selin_plan__plan_da_2a5470_idx',
        ),
        migrations.RenameIndex(
            model_name='bargingplan',
            new_name='selling_pla_barge_c_59946a_idx',
            old_name='selin_plan__barge_c_b2b3bd_idx',
        ),
        migrations.RenameIndex(
            model_name='bargingplan',
            new_name='selling_pla_no_plan_850e47_idx',
            old_name='selin_plan__no_plan_6815ee_idx',
        ),
        migrations.AlterModelTable(
            name='bargingplan',
            table='selling_plan_barging',
        ),
    ]
