# Generated by Django 5.1.8 on 2026-03-07 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('required_perms', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
            ],
            options={
                'db_table': 'core_menu_items',
                'ordering': ['heading', 'order'],
            },
        ),
    ]
