# Generated by Django 5.1.8 on 2026-06-13 03:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_chat_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('report_type', models.CharField(max_length=100)),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reports', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analytics.aichatsession')),
            ],
            options={
                'db_table': 'ai_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('message', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='analytics.aichatsession')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='analytics.aireport')),
            ],
            options={
                'db_table': 'ai_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportManagement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_code', models.CharField(blank=True, max_length=80, null=True)),
                ('title', models.CharField(default='Operations Management Report', max_length=150)),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('range', 'Custom range')], default='weekly', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('week', models.PositiveIntegerField(blank=True, null=True)),
                ('period_key', models.CharField(max_length=30)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=30)),
                ('summary_cards', models.JSONField(blank=True, default=list)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('hse_incidents', models.IntegerField(default=0)),
                ('total_production', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_barging', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_movement', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_inventory', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('avg_ni', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stockpile_count', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('iup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.mineiup')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_management_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_management',
            },
        ),
        migrations.CreateModel(
            name='ReportManagementDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=150, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('IMAGE', 'Image'), ('LINK', 'Link'), ('OTHER', 'Other')], default='PDF', max_length=30, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/management/%Y/%m/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='analytics.reportmanagement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_management_document',
            },
        ),
        migrations.CreateModel(
            name='ReportManagementManpower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contractor', models.CharField(max_length=100)),
                ('personnel', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('source_module', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_rows', to='analytics.reportmanagement')),
            ],
            options={
                'db_table': 'report_management_manpower',
            },
        ),
        migrations.CreateModel(
            name='ReportManagementMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('SUMMARY', 'Summary'), ('HSE', 'HSE'), ('FLEET', 'Fleet'), ('BARGING', 'Barging'), ('INVENTORY', 'Inventory'), ('QUALITY', 'Quality'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], default='SUMMARY', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_module', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.reportmanagement')),
            ],
            options={
                'db_table': 'report_management_metric',
            },
        ),
        migrations.CreateModel(
            name='ReportManagementMining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=100)),
                ('plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('achievement', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('group', models.CharField(choices=[('ORE', 'Ore'), ('WASTE', 'Waste'), ('BARGING', 'Barging'), ('TOTAL', 'Total')], default='ORE', max_length=30)),
                ('is_total', models.BooleanField(default=False)),
                ('is_grand_total', models.BooleanField(default=False)),
                ('source_module', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_rows', to='analytics.reportmanagement')),
            ],
            options={
                'db_table': 'report_management_mining',
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=100)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/%d/')),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_export_job',
                'indexes': [models.Index(fields=['module'], name='report_expo_module_7ba232_idx'), models.Index(fields=['status'], name='report_expo_status_ef6564_idx'), models.Index(fields=['created_at'], name='report_expo_created_d181da_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reportmanagement',
            index=models.Index(fields=['iup', 'period_type', 'period_key'], name='report_mana_iup_id_5eff55_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmanagement',
            index=models.Index(fields=['year', 'month', 'week'], name='report_mana_year_0baf90_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmanagement',
            index=models.Index(fields=['period_start', 'period_end'], name='report_mana_period__9c03c2_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmanagement',
            index=models.Index(fields=['status'], name='report_mana_status_c9d01c_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportmanagement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('iup', 'period_type', 'period_key'), name='unique_report_management_period_active'),
        ),
        migrations.AddIndex(
            model_name='reportmanagementdocument',
            index=models.Index(fields=['report', 'sort_order'], name='report_mana_report__263899_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmanagementdocument',
            index=models.Index(fields=['document_type'], name='report_mana_documen_e6540c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmanagementdocument',
            index=models.Index(fields=['document_date'], name='report_mana_documen_7bff7e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmanagementmanpower',
            index=models.Index(fields=['report', 'sort_order'], name='report_mana_report__c621ab_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmanagementmanpower',
            index=models.Index(fields=['contractor'], name='report_mana_contrac_96a7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmanagementmetric',
            index=models.Index(fields=['report', 'section', 'sort_order'], name='report_mana_report__50f2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmanagementmetric',
            index=models.Index(fields=['section'], name='report_mana_section_97d859_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmanagementmining',
            index=models.Index(fields=['report', 'sort_order'], name='report_mana_report__ebf7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmanagementmining',
            index=models.Index(fields=['material'], name='report_mana_materia_fdb47d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmanagementmining',
            index=models.Index(fields=['group'], name='report_mana_group_4ad786_idx'),
        ),
    ]
