# Generated by Django 5.1.8 on 2026-05-20 00:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('master', '0004_mineunitsexportview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodWeeklyReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_code', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(default='Operations Scorecard', max_length=150)),
                ('year', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=30)),
                ('summary_cards', models.JSONField(blank=True, default=list)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('iup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.mineiup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bod_weekly_report',
            },
        ),
        migrations.CreateModel(
            name='BodWeeklyMining',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=100)),
                ('weekly_plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('achievement', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('is_total', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('iup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.mineiup')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_rows', to='analytics.bodweeklyreport')),
            ],
            options={
                'db_table': 'bod_weekly_mining',
            },
        ),
        migrations.CreateModel(
            name='BodWeeklyMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('SUMMARY', 'Summary'), ('HSE', 'HSE'), ('FLEET', 'Fleet'), ('BARGING', 'Barging'), ('INVENTORY', 'Inventory'), ('OTHER', 'Other')], default='SUMMARY', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('iup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.mineiup')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.bodweeklyreport')),
            ],
            options={
                'db_table': 'bod_weekly_metric',
            },
        ),
        migrations.CreateModel(
            name='BodWeeklyManpower',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contractor', models.CharField(max_length=100)),
                ('personnel', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('iup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.mineiup')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_rows', to='analytics.bodweeklyreport')),
            ],
            options={
                'db_table': 'bod_weekly_manpower',
            },
        ),
        migrations.CreateModel(
            name='BodWeeklyDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=150, null=True)),
                ('document_type', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('IMAGE', 'Image'), ('LINK', 'Link'), ('OTHER', 'Other')], default='PDF', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='bod/weekly-reports/%Y/%m/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('iup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.mineiup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='analytics.bodweeklyreport')),
            ],
            options={
                'db_table': 'bod_weekly_document',
            },
        ),
        migrations.AddIndex(
            model_name='bodweeklyreport',
            index=models.Index(fields=['iup', 'year', 'week'], name='bod_weekly__iup_id_844248_idx'),
        ),
        migrations.AddIndex(
            model_name='bodweeklyreport',
            index=models.Index(fields=['period_start', 'period_end'], name='bod_weekly__period__6cf349_idx'),
        ),
        migrations.AddIndex(
            model_name='bodweeklyreport',
            index=models.Index(fields=['status'], name='bod_weekly__status_cb401f_idx'),
        ),
        migrations.AddConstraint(
            model_name='bodweeklyreport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('iup', 'year', 'week'), name='unique_bod_weekly_report_by_iup_year_week_active'),
        ),
        migrations.AddIndex(
            model_name='bodweeklymining',
            index=models.Index(fields=['report', 'sort_order'], name='bod_weekly__report__28a1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='bodweeklymining',
            index=models.Index(fields=['material'], name='bod_weekly__materia_62612b_idx'),
        ),
        migrations.AddIndex(
            model_name='bodweeklymetric',
            index=models.Index(fields=['report', 'section', 'sort_order'], name='bod_weekly__report__2c5389_idx'),
        ),
        migrations.AddIndex(
            model_name='bodweeklymetric',
            index=models.Index(fields=['section'], name='bod_weekly__section_5bc99a_idx'),
        ),
        migrations.AddIndex(
            model_name='bodweeklymanpower',
            index=models.Index(fields=['report', 'sort_order'], name='bod_weekly__report__d1c78b_idx'),
        ),
        migrations.AddIndex(
            model_name='bodweeklymanpower',
            index=models.Index(fields=['contractor'], name='bod_weekly__contrac_688414_idx'),
        ),
        migrations.AddIndex(
            model_name='bodweeklydocument',
            index=models.Index(fields=['report', 'sort_order'], name='bod_weekly__report__a0ff4e_idx'),
        ),
        migrations.AddIndex(
            model_name='bodweeklydocument',
            index=models.Index(fields=['document_type'], name='bod_weekly__documen_748bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='bodweeklydocument',
            index=models.Index(fields=['document_date'], name='bod_weekly__documen_59c0e2_idx'),
        ),
    ]
