# Generated by Django 5.1.8 on 2026-07-20 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportManagementTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'report_management_target',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='reportmanagementmetric',
            options={'ordering': ['sort_order', 'title']},
        ),
        migrations.AddField(
            model_name='reportmanagementmetric',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='reportmanagementmetric',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reportmanagementmetric',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reportmanagementmetric',
            index=models.Index(fields=['report', 'code'], name='report_mana_report__ab78d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportmanagementmetric',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('report', 'code'), name='unique_report_management_metric_code'),
        ),
        migrations.AddField(
            model_name='reportmanagementtarget',
            name='iup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.mineiup'),
        ),
        migrations.AddField(
            model_name='reportmanagementtarget',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='analytics.reportmanagement'),
        ),
        migrations.AddIndex(
            model_name='reportmanagementtarget',
            index=models.Index(fields=['report', 'code'], name='report_mana_report__be6327_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportmanagementtarget',
            constraint=models.UniqueConstraint(fields=('report', 'code'), name='unique_report_management_target_code'),
        ),
    ]
