# Generated by Django 5.1.8 on 2026-05-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_bodweeklyreport_bodweeklymining_bodweeklymetric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodweeklydocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('IMAGE', 'Image'), ('LINK', 'Link'), ('OTHER', 'Other')], default='PDF', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bodweeklydocument',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
