# Generated by Django 5.1.8 on 2026-05-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_bodweeklydocument_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodweeklydocument',
            name='code',
        ),
        migrations.RemoveField(
            model_name='bodweeklydocument',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bodweeklydocument',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='bodweeklydocument',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='bodweeklydocument',
            name='iup',
        ),
        migrations.RemoveField(
            model_name='bodweeklydocument',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bodweeklymanpower',
            name='code',
        ),
        migrations.RemoveField(
            model_name='bodweeklymanpower',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bodweeklymanpower',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='bodweeklymanpower',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='bodweeklymanpower',
            name='iup',
        ),
        migrations.RemoveField(
            model_name='bodweeklymanpower',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bodweeklymetric',
            name='code',
        ),
        migrations.RemoveField(
            model_name='bodweeklymetric',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bodweeklymetric',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='bodweeklymetric',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='bodweeklymetric',
            name='iup',
        ),
        migrations.RemoveField(
            model_name='bodweeklymetric',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bodweeklymining',
            name='code',
        ),
        migrations.RemoveField(
            model_name='bodweeklymining',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bodweeklymining',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='bodweeklymining',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='bodweeklymining',
            name='iup',
        ),
        migrations.RemoveField(
            model_name='bodweeklymining',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bodweeklymanpower',
            name='source_module',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='bodweeklymetric',
            name='source_module',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='bodweeklymining',
            name='group',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('BARGING', 'Barging'), ('TOTAL', 'Total')], default='PRODUCTION', max_length=30),
        ),
        migrations.AddField(
            model_name='bodweeklymining',
            name='is_grand_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bodweeklymining',
            name='source_module',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=20),
        ),
    ]
