# Generated by Django 5.1.8 on 2026-05-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_bodweeklydocument_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodweeklymining',
            name='group',
            field=models.CharField(choices=[('ORE', 'Ore'), ('WASTE', 'Waste'), ('BARGING', 'Barging'), ('TOTAL', 'Total')], default='PRODUCTION', max_length=30),
        ),
    ]
