# Generated by Django 5.1.8 on 2026-06-21 00:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=80)),
                ('file', models.FileField(upload_to='imports/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_job',
            },
        ),
        migrations.CreateModel(
            name='ImportJobRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importjob')),
            ],
            options={
                'db_table': 'import_job_row',
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['module'], name='import_job_module_a69cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status'], name='import_job_status_7cd937_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['created_at'], name='import_job_created_d7bb74_idx'),
        ),
        migrations.AddIndex(
            model_name='importjobrow',
            index=models.Index(fields=['job', 'status'], name='import_job__job_id_ef2651_idx'),
        ),
        migrations.AddIndex(
            model_name='importjobrow',
            index=models.Index(fields=['job', 'row_number'], name='import_job__job_id_711b58_idx'),
        ),
    ]
