# Generated by Django 5.1.8 on 2026-06-17 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_ore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='is_production',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='categories',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_production'], name='master_mate_is_prod_180e46_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_ore'], name='master_mate_is_ore_749aff_idx'),
        ),
    ]
