# Generated by Django 5.1.8 on 2026-03-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='miningactivitycategories',
            new_name='master_acti_name_e4fae2_idx',
            old_name='mine_activi_name_aa0f66_idx',
        ),
        migrations.RenameIndex(
            model_name='miningactivitycategories',
            new_name='master_acti_categor_ad6e2d_idx',
            old_name='mine_activi_categor_19ce1e_idx',
        ),
        migrations.AlterModelTable(
            name='miningactivity',
            table='master_activity',
        ),
        migrations.AlterModelTable(
            name='miningactivitycategories',
            table='master_activity_categories',
        ),
        migrations.AlterModelTable(
            name='miningactivitylocation',
            table='master_activity_locations',
        ),
    ]
