# Generated by Django 5.1.8 on 2026-04-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_rename_mine_activi_name_aa0f66_idx_master_acti_name_e4fae2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellingsurveyor',
            name='code',
        ),
        migrations.RemoveField(
            model_name='sellingsurveyor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sellingsurveyor',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='sellingsurveyor',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='sellingsurveyor',
            name='iup',
        ),
        migrations.RemoveField(
            model_name='sellingsurveyor',
            name='updated_at',
        ),
    ]
