# Generated by Django 5.1.8 on 2026-06-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_material_is_ore_material_is_production_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='material',
            name='master_mate_categor_f65c93_idx',
        ),
        migrations.RemoveField(
            model_name='material',
            name='categories',
        ),
    ]
