# Generated by Django 5.1.8 on 2026-04-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_sellingsurveyor_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineUnitsExportView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit_vendor', models.CharField(blank=True, max_length=60, null=True)),
                ('unit_code', models.CharField(blank=True, max_length=25, null=True)),
                ('unit_model', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_class', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=150, null=True)),
                ('id_category', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('id_vendor', models.IntegerField(blank=True, null=True)),
                ('supports', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('commisioning_date', models.DateField(blank=True, null=True)),
                ('on_hire', models.DateField(blank=True, null=True)),
                ('off_hire', models.DateField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('iup_id', models.IntegerField(blank=True, null=True)),
                ('iup_code', models.CharField(blank=True, max_length=25, null=True)),
                ('iup_name', models.CharField(blank=True, max_length=100, null=True)),
                ('assignment_start_date', models.DateField(blank=True, null=True)),
                ('assignment_end_date', models.DateField(blank=True, null=True)),
                ('assignment_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_master_units',
                'managed': False,
            },
        ),
    ]
