# Generated by Django 5.1.8 on 2026-06-17 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_material_master_mate_categor_f65c93_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampletype',
            name='category',
        ),
        migrations.AddField(
            model_name='material',
            name='sale_adjust',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sampletype',
            name='is_geology',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sampletype',
            name='is_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampletype',
            name='is_production',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sampletype',
            name='is_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['sale_adjust'], name='master_mate_sale_ad_a8c48b_idx'),
        ),
    ]
