# Generated by Django 5.1.8 on 2026-06-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_remove_sampletype_category_material_sale_adjust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletype',
            name='batch_pattern',
            field=models.CharField(blank=True, help_text='Example: {type}{material}{truck}{point}{batch}', max_length=255, null=True),
        ),
    ]
