# Generated by Django 5.1.8 on 2026-06-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oreproductions',
            name='sample_type',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
