# Generated by Django 5.1.8 on 2026-03-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oreproductions',
            name='tonnage',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True),
        ),
    ]
