# Generated by Django 5.1.8 on 2026-06-15 07:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplesPsiView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_sample', models.DateField(blank=True, default=None, null=True)),
                ('type_sample', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('material_psi', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('stockpile', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dome_psi', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('batch_code', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('total_ore', models.FloatField(blank=True, default=None, null=True)),
                ('allocated_tonnage', models.FloatField(blank=True, default=None, null=True)),
                ('sample_id', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('ni', models.FloatField(blank=True, default=None, null=True)),
                ('co', models.FloatField(blank=True, default=None, null=True)),
                ('al2o3', models.FloatField(blank=True, default=None, null=True)),
                ('cao', models.FloatField(blank=True, default=None, null=True)),
                ('cr2o3', models.FloatField(blank=True, default=None, null=True)),
                ('fe2o3', models.FloatField(blank=True, default=None, null=True)),
                ('fe', models.FloatField(blank=True, default=None, null=True)),
                ('mgo', models.FloatField(blank=True, default=None, null=True)),
                ('sio2', models.FloatField(blank=True, default=None, null=True)),
                ('sm', models.FloatField(blank=True, default=None, null=True)),
                ('mc', models.FloatField(blank=True, default=None, null=True)),
                ('iup_id', models.IntegerField(blank=True, default=None, null=True)),
                ('iup_code', models.CharField(blank=True, default=None, max_length=25, null=True)),
            ],
            options={
                'db_table': 'view_geology_sample_psi',
                'managed': False,
            },
        ),
    ]
