# Generated by Django 5.1.8 on 2026-06-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0002_samplespsiview'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('adjust_sale', models.CharField(max_length=50, unique=True)),
                ('material_code', models.CharField(max_length=25)),
                ('selling_type', models.CharField(max_length=25)),
                ('monitoring_type', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_quality_config',
                'indexes': [models.Index(fields=['adjust_sale'], name='master_qual_adjust__2b7299_idx'), models.Index(fields=['material_code'], name='master_qual_materia_a50845_idx'), models.Index(fields=['is_active'], name='master_qual_is_acti_4906a0_idx')],
            },
        ),
    ]
