# Generated by Django 5.1.8 on 2026-03-18 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0002_alter_oreproductions_tonnage'),
        ('master', '0002_rename_mine_activi_name_aa0f66_idx_master_acti_name_e4fae2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='domemerge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domemerge',
            name='dome_second',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_targets', to='master.sourceminesdome'),
        ),
        migrations.AlterField(
            model_name='domemerge',
            name='original_dome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_sources', to='master.sourceminesdome'),
        ),
        migrations.AlterField(
            model_name='domemerge',
            name='ref_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='domemerge',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='domemerge',
            name='tonnage_primary',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='domemerge',
            name='tonnage_second',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddIndex(
            model_name='domemerge',
            index=models.Index(fields=['ref_id'], name='geology_dom_ref_id_33083e_idx'),
        ),
    ]
