# Generated by Django 5.1.8 on 2026-06-17 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0003_qualityconfig'),
        ('master', '0004_remove_sampletype_category_material_sale_adjust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityconfig',
            name='monitoring_sample_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_monitoring_configs', to='master.sampletype'),
        ),
        migrations.AddField(
            model_name='qualityconfig',
            name='selling_sample_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_selling_configs', to='master.sampletype'),
        ),
    ]
