# Generated by Django 5.1.8 on 2026-03-18 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0003_alter_domemerge_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='domemerge',
            name='is_undone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domemerge',
            name='undo_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domemerge',
            name='undone_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domemerge',
            name='undone_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dome_merge_undo_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='domemerge',
            name='status',
            field=models.CharField(default='MERGED', max_length=20),
        ),
    ]
