# Generated by Django 5.1.8 on 2026-06-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0004_qualityconfig_monitoring_sample_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityconfig',
            name='monitoring_type',
        ),
        migrations.RemoveField(
            model_name='qualityconfig',
            name='selling_type',
        ),
    ]
