# Generated by Django 5.1.8 on 2026-03-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0004_domemerge_is_undone_domemerge_undo_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domemerge',
            name='status',
            field=models.CharField(default='MERGED', max_length=50),
        ),
    ]
