# Generated by Django 5.1.8 on 2026-06-18 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0005_remove_qualityconfig_monitoring_type_and_more'),
        ('master', '0004_remove_sampletype_category_material_sale_adjust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityconfig',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_configs', to='master.material'),
        ),
    ]
