# Generated by Django 5.1.8 on 2026-03-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0005_alter_domemerge_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domemerge',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oreproductions',
            name='dome_compositing',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
