# Generated by Django 5.1.8 on 2026-06-18 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0006_qualityconfig_material'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='qualityconfig',
            name='master_qual_materia_a50845_idx',
        ),
        migrations.RemoveField(
            model_name='qualityconfig',
            name='material_code',
        ),
    ]
