# Generated by Django 5.1.8 on 2026-04-11 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0007_detailsmral_detailsroa_delete_stockpilemerge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCrmCertified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oreas_name', models.CharField(blank=True, max_length=25, null=True)),
                ('ni', models.FloatField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('cao', models.FloatField(blank=True, null=True)),
                ('cr2o3', models.FloatField(blank=True, null=True)),
                ('fe2o3', models.FloatField(blank=True, null=True)),
                ('fe', models.FloatField(blank=True, null=True)),
                ('k2o', models.FloatField(blank=True, null=True)),
                ('mgo', models.FloatField(blank=True, null=True)),
                ('mno', models.FloatField(blank=True, null=True)),
                ('na2o', models.FloatField(blank=True, null=True)),
                ('p2o5', models.FloatField(blank=True, null=True)),
                ('p', models.FloatField(blank=True, null=True)),
                ('sio2', models.FloatField(blank=True, null=True)),
                ('tio2', models.FloatField(blank=True, null=True)),
                ('s', models.FloatField(blank=True, null=True)),
                ('cu', models.FloatField(blank=True, null=True)),
                ('zn', models.FloatField(blank=True, null=True)),
                ('ci', models.FloatField(blank=True, null=True)),
                ('so3', models.FloatField(blank=True, null=True)),
                ('loi', models.FloatField(blank=True, null=True)),
                ('sm', models.FloatField(blank=True, null=True)),
                ('al2o3', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sample CRM Certified',
                'verbose_name_plural': 'Sample CRM Certified',
                'db_table': 'geology_sample_crm_certified',
                'indexes': [models.Index(fields=['oreas_name'], name='geology_sam_oreas_n_247760_idx')],
            },
        ),
    ]
