# Generated by Django 5.1.8 on 2026-06-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0007_remove_qualityconfig_master_qual_materia_a50845_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='samplesNoOrders',
        ),
    ]
