# Generated by Django 5.1.8 on 2026-06-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0008_delete_samplesnoorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='samplesNaPds',
        ),
    ]
