# Generated by Django 5.1.8 on 2026-06-20 04:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0009_delete_samplesnapds'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplesPdsNaView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_sample', models.DateField(blank=True, default=None, null=True)),
                ('shift', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('type_sample', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('sample_method', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('is_production', models.BooleanField(default=True)),
                ('material', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('sampling_area', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sampling_point', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('batch', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('increments', models.IntegerField(blank=True, default=None, null=True)),
                ('sample_weight', models.FloatField(blank=True, default=None, null=True)),
                ('sample_number', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('ni', models.FloatField(blank=True, default=None, null=True)),
                ('co', models.FloatField(blank=True, default=None, null=True)),
                ('al2o3', models.FloatField(blank=True, default=None, null=True)),
                ('cao', models.FloatField(blank=True, default=None, null=True)),
                ('cr2o3', models.FloatField(blank=True, default=None, null=True)),
                ('fe2o3', models.FloatField(blank=True, default=None, null=True)),
                ('fe', models.FloatField(blank=True, default=None, null=True)),
                ('mgo', models.FloatField(blank=True, default=None, null=True)),
                ('sio2', models.FloatField(blank=True, default=None, null=True)),
                ('mc', models.FloatField(blank=True, default=None, null=True)),
                ('sm', models.FloatField(blank=True, default=None, null=True)),
                ('iup_id', models.IntegerField(blank=True, default=None, null=True)),
                ('iup_code', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('iup_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'db_table': 'view_geology_sample_pds_na',
                'managed': False,
            },
        ),
    ]
