# Generated by Django 5.1.8 on 2026-05-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0009_samplecrmmralview_samplecrmroaview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTypeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_sample', models.DateField(blank=True, default=None, null=True)),
                ('sample_number', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('type_sample', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('sample_method', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('delivery', models.DateTimeField(blank=True, default=None, null=True)),
                ('waybill_number', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('mral_order', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('roa_order', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('date_production', models.DateTimeField(blank=True, default=None, null=True)),
                ('release_mral', models.DateTimeField(blank=True, default=None, null=True)),
                ('release_roa', models.DateTimeField(blank=True, default=None, null=True)),
                ('iup_id', models.IntegerField(blank=True, default=None, null=True)),
                ('iup_code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('iup_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'view_sample_type_count',
                'managed': False,
            },
        ),
    ]
