# Generated by Django 5.1.8 on 2026-05-19 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0010_sampletypecount'),
        ('master', '0004_mineunitsexportview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listtemporary',
            table='view_waybill_temporary',
        ),
        migrations.CreateModel(
            name='ProductionsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('iup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.mineiup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'geology_productions_config',
                'indexes': [models.Index(fields=['key'], name='geology_pro_key_e2aedf_idx'), models.Index(fields=['value'], name='geology_pro_value_3a0ce7_idx')],
            },
        ),
    ]
