# Generated by Django 5.1.8 on 2026-05-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0011_alter_listtemporary_table_productionsconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionsconfig',
            name='code',
        ),
        migrations.RemoveField(
            model_name='productionsconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productionsconfig',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='productionsconfig',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='productionsconfig',
            name='iup',
        ),
        migrations.RemoveField(
            model_name='productionsconfig',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productionsconfig',
            name='user',
        ),
    ]
